SNSKBbDOHBTHASOBjFKFI@-CBTDUNWSNHInIFPHUKCHABDOHBTPOBUBBQBU^THRICSBKKTFTSHU^SOBQNEUFISEBFSTHASOBjFKFI@UBTHIFSBPNSOWKF^ARKBIBU@^	-WUHJWSbIBU@BSNDuNI@SHIB
NITWNUBCSUFDLQNEUFISEBFSTDFSDO^JBKHC^UO^SOJNDWBUDRTTNHIC^IFJNDT^ISOTWKF^ARKJFKBQHDFKKNQBK^FICTWNUNSBCQNEB-DHQBUfUSwUHJWSfETSUFDSTHRICPFQBTNIIBHIDHKHUTJHCBUIFICCN@NSFKFBTSOBSNDQNEUFISFICB^B
DFSDONI@ARSRUNTSNDCBTN@IDHHKFRCNHPFQBTBAABDS-TA_BKBDSUHINDEBBWTUO^SOJNDDONJBTCN@NSFKDONUWTBDOHNI@SHIBT-QHDFKTJFKBQHDFKUO^SOJNDFICKNQBK^BDOHNI@OFUJHINBTWKF^ARKFICEUN@OS-QHDFKTtSURDSRUBCWHWTSBWSUFDLPNSO@HHCNISUHFICINDBHRSUHNIDKRCNI@THJBCUHWTPNSOJBKHCNDJFKBQHDFK-LB^PHUCTWHWBKBDSUHINDCFIDBNICNBTHRICSUFDLHTSQNEUFISWKF^ARKCN@NSFKJHCBUIIBHIQNEBT-DHCBiFJBeFEENSS-EWJ-@BIUBnIWRS-WUHJWSnIWRSsUFDLNITWNUBCE^uNI@SHIBT
jFIIJFTSjFKFI@htsuNI@SHIBJFIIJFTSJFKFI@HTSUNI@SHIBCFINTOSFNJHUTFOFUOFTOJNUNI@SHIB	rTBTNJNKFUJRTNDFKQNEBJHHCTS^KB@BIUBNITSURJBIST	-KBSSBUe-NIDKRCBqHDFKaFKTB-FWWqBUTNHIQ-CRUFSNHI--K^UNDT|NISUH
CN@NSFKDONJBz--|QBUTB
KNQBK^BDOHBTz-uNI@NI@SOUHR@OSOBFNUFTSHU^RISHKC-bQBU^EBFSFWRKTBFUO^SOJEHKC--|DOHURT
QNEUFISPFQBz-HHHH-NNNN--|EUNC@B
BDOHCFIDBz-aBBKSOBBDOHBTCFIDBNISOBTHRIC-kHTSNISOBPFQBTPOBUBCUBFJTFUBAHRIC--|HRSUH
AFCNI@DONJBTz--dUBFSBCE^fswKF^BU-OSSWTPPP	FSWKF^BU	DHJ--dHW^UN@OSåŽfLSNTnID	