C^C[R
{BZ^YXBDdRERYVSR=SRDTE^GC^XY
vCV[RXQ[^P_CVYSV[[BER@_RERRARENYXCRSVYTRDBYSREC_RPX[SRYRZUEVTRXQC_RDBY~YDG^ERSUNC_RA^UEVYCDCN[RXQryyntVYSzVD^[XYNVY^=GEXZGC
rYREPRC^TvQEXURVC@VEZPB^CVEE^QQDE_NC_Z^TGRETBDD^XYDZXXC_UEVDDR[RZRYCDBG[^QC^YPPEXXAR_VEZXY^XBDZV[RVYSQRZV[RAXTV[DDXB[QB[VYSA^UEVYCZXXS=TXAREvECgEXZGC
a^UEVYCT^CNDTVGRVCDBYDRC^YQBDRS@^C_PX[SRY_BRD[^AR[NDCERRCDTRYRDTXYCRZGXEVENvQEXQBCBE^DC^TDCN[RSNYVZ^TVYSTX[XEQB[TVGCBE^YPC_RRDDRYTRXQZXARZRYCVYS]XN=DQO
DXQCDCERRCT_VCCRES^DCVYCSEBZURVCDVZU^RYCT^CNYX^DRE_NC_Z^TQXXCDCRGD=AXTV[D
ZV[RVYSQRZV[RSBRCDXB[QB[_VEZXY^RDE_NC_Z^T^YCREG[VNROGERDD^ARVYS[^AR[N=AXTV[DdCEBTCBERS
VQEXURVCCEVT\@^C_RYPVP^YP^YCEXVYSDZXXC_XBCEXQRVCBE^YPSNYVZ^TAXTV[^YCREG[VNVYSRYREPRC^TE_NC_ZD=\RN@XESD
VQEXURVC@XE[SZBD^TDXB[QBY\SVYTRA^UEVYCBG[^QC^YPryyntzVD^[XYNVY^VQEXQBD^XYE_NC_Z^TDRERYVSRDXB[QB[A^URDBEUVYDCN[R=TXSRyVZR
{X[^CV=UGZ
=PRYER~YGBC
=GEXZGC~YGBC
cEVT\^YDG^ERSUNryyntRYYNtfBRRYC_RRaXTV[^DCVYSzVD^[XYNVY^bDRD^Z^[VEZBD^TV[A^URZXXSDCN[RPRYER^YDCEBZRYCD=[RCCRE
{=^YT[BSRaXTV[
qV[DR=VGGaRED^XY
A=SBEVC^XY
==[NE^TD
l^YCEXE_NC_Zj=dXQC_BZZ^YP=XXXXXXXV___==lAREDRÕ·¤{^P_CsVYTRj=~YC_RP[X@XQC_RRARY^YPDBY=`RD@VNCXC_RVYT^RYCSEBZ=`_^DGREDXQ]XN^YRARENDCRG=bYSREC_RD\N@RE^DRVYSTXYYRTC=XXXXXNRVVV==lt_XEBDÕ·¤pX[SRYpEXXARj={BZ^YXBDDRERYVSR=~YC_RDCERRCD@_RERSERVZDVERZVSR=RVECDURVCCXC_RA^UEVYCD@VN=sVYTR@^C_ZRQRR[C_RSVN=XXXXXXXXXX==luE^SPRrT_X^YP{^P_Cj=qRR[C_RE_NC_ZCV\RNXB_^P_=cXPRC_RE@RCXBT_C_RD\N=v__V____==lAREDRj=tX[XEDU[RYS^YC_RY^P_CÕ·®DRZUEVTR=rARENZXZRYCVD@RRCCEVTR=c_EXBP_C_R[VBP_CREVYSC_RDXBYS=xBEDG^E^CD[^QCXQQC_RPEXBYS==lt_XEBDÕ·¤pX[SRYpEXXARj={BZ^YXBDDRERYVSR=~YC_RDCERRCD@_RERSERVZDVERZVSR=RVECDURVCCXC_RA^UEVYCD@VN=sVYTR@^C_ZRQRR[C_RSVN=XXXXXXXXXX==lXBCEXqVS^YPp[X@j=dXQC_BZZ^YP=V______XXXXXX==tERVCRSUNvcg[VNRE=_CCGD@@@VCG[VNRETXZ==tXGNE^P_Cõžv\C^D~YT