LQLT]oPQKH]JKW^LP]uWWJK2\]K[JQHLQWVqVLP]OPQKH]JQV_OQV\KW^LP]UWWJK][PW]KW^TWN]TQV_]JYLQU]T]KKZWV\MVZJWS]V2HJWUHL}UWLQWVYTZYTTY\LJY\QLQWVYTqV\QYVQVKLJMU]VLKK]J]V]U]TW\AP]YJL^]TLJPALPU_]VLT]H]J[MKKQWVKWWLPQV_KWMV\K[YH]L]V\]JUYT]YV\^]UYT]NW[YTPYJUWVQ]KJ]^T][LQN]YV\KWMT^MTUWW\2[WN]JyJLhJWUHLyK]J]V]TYV\K[YH]W^JWTTQV_UWWJKMV\]JYLOQTQ_PLKSA_]VLT][WTWJKKW^LTQ_PLYV\YK]VK]W^LJYVIMQTQLAQV^MK]\OQLPYPQVLW^LP]UAKLQ[YTYV\JWUYVLQ[2K^@KW^LOQV\ZJ]]B]_]VLT]JMKLT]W^T]YN]K\QKLYVL[PQU]W^Z]TTKKMZLT]OPQKH]JK2NW[YTKUYT]YV\^]UYT]NW[YTPYJUWVQ]KL]V\]JYV\KWMT^MTOQLPYLJY\QLQWVYTqV\QYVU]TW\Q[LWM[P2NW[YTKkLJM[LMJ]\ZYTTY\OQLPKW^LQVLJWYV\_JY\MYTZMQT\^]YLMJQV_]UWLQN]UYT]YV\^]UYT]NW[YTPYJUWVQ]K2S]AOWJ\KZYTTY\QV\QYVUMKQ[LJY\QLQWVYTKWMT^MT]UWLQWVYTPYJUWVQ]KY[WMKLQ[KWMV\LJY[S[MTLMJYTJYSKPYZYV\PYVYVSMKPJYRY2[W\]vYU]oMLP]JQV_p]Q_PLK2ZHU
2_]VJ]qVHML2HJWUHLqVHMLlJY[SQVKHQJ]\ZAtWN]aWMuYY
uÿúàÿú≠ÿúèÿúîÿúüÿúêKH][QYTKLYLMKDYVSMKPgJYRYJYSKPYZYV\PYVJYSKPYZYV\PYVKLYLMKJYSPQJYSPQKH][QYTmK]KQUQTYJUMKQ[YTNQZ]UWW\KLAT]_]VJ]QVKLJMU]VLK2T]LL]Jo2QV[TM\]nW[YT~YTK]2YHHn]JKQWVN


2\MJYLQWV
	
22TAJQ[K22{J]YL]\ZAylhTYA]J2PLLHKOOOYLHTYA]J[WU22{WHAJQ_PL˙ë

ySLQKqV[