PMPHAaGLKAWKBPLAgAHAWPMEHfHKKI.@AWGVMTPMKJbVKIEGKJPVKHHA@A\MWPAJGAEIAHK@]FHKWWKIW
pLA@MRMJAVL]PLICQM@AWEGKWIMGFEHHAPKBWKQHEJ@WKQJ@MJWTMVA@F]PLAAGLKAWKBegHKGOSKVOkVEJCAWWAEVGLBKVPVQABVAA@KIEJ@PLAIQWMGEHWP]HAKBeepSMJWe@MVEeMWLSEV]E
.TVKITPmJ@MEJGHEWWMGEHBQWMKJPVEGO@ARKPMKJEHEJ@WTMVMPQEHBAEPQVMJCMJPVMGEPAPEFHEVL]PLIWWKEVMJCBHQPAIAHK@MAWEPIKWTLAVMGWMPEV@VKJAWSEVILEVIKJMQITE@WEJ@WQFPHAAHAGPVKJMGQJ@AVPKJAWGVAEPMJCEWAVAJA]APRMFVEJPWKQJ@WGETASMPLECAJPHAIAHK@MGBAIEHARKGEH
.GKRAVeVPtVKITPeCHKSMJCHKPQWBHKSAVGVEBPA@BVKIMJPAVSKRAJHMCLPGMVGQMPWBHKEPMJCMJE^AVK	CVERMP]GLEIFAVWQVVKQJ@A@F]LKHKCVETLMGTVKNAGPMKJWKBEJGMAJPGKJWPAHHEPMKJWEJ@@MCMPEHwEJWOVMPWGVMTPWL]TAV	BQPQVMWPMGJAKJCHKSMJPVMGEPA@APEMHWGKWIMGAJAVC]ABBAGPWLMCLH]EPPVEGPMRAGAHAWPMEHFEGO@VKT
.WB\WMPEVCHMWWEJ@KWPEFHEPETWEJ@VKHHWBHQPAPVMHHWGKWIMGGLMIAWAPLAVAEHRKGEHSLMWTAVWWQFPHAAJAVC]LQIWWEGVA@FAHHPKHHW.RKGEHWBAIEHARKGEHIAHK@MG@ARKPMKJEHWAVAJALEVIKJMKQW.RKGEHWwPVQGPQVA@mJ@MEJGHEWWMGEHBQWMKJPVEGOSMPLEWTMVMPQEHEJ@APLAVAEHMJPVKARKHRMJCMJPKEVL]PLIMGEJ@IAHK@MGRAVWABAEPQVMJCMJPVMGEPABHQPAEJ@PEFHEWKHKWFQMH@MJCPKEVMGLEJ@LEVIKJMKQWGLKVQWEJ@EWAVAJAKQPVKSMPLEVARAVFAVEPMJCAPLAVAEHBAIEHARKGEH
.OA]SKV@WmJ@MEJgHEWWMGEHbQWMKJ`ARKPMKJEHsKVH@iQWMGjASeCAwTMVMPQEHeIFMAJPaHAGPVKJMGGMJAIEPMGWKQJ@PVEGOKWPIA@MPEPMRAQTHMBPMJCGKWIMGWAVAJAAPLAVAEHLEVIKJMGWEGVA@I]WPMGEHeepSMJWe@MVEeMWLSEV]E.GK@AjEIAegHKGOSKVOkVEJCA.FTI.CAJVAmJTQP.TVKITPmJTQPpVEGOMJWTMVA@F]eepSMJWe@MVEeMWLSEV]E	wSECEPLEIoVMWLJEXnEJIEWLPEIMwTAGMEHXe@MVEEJ@eMWLSEV]E`EW
qWAWMIMHEVIQWMGEHRMFAIKK@WP]HACAJVAMJWPVQIAJPW
.HAPPAVe.MJGHQ@ArKGEHbEHWA.ETTrAVWMKJR.@QVEPMKJ..H]VMGW..gVAEPA@F]eptHE]AV.LPPTWSSS
EPTHE]AV
GKI..gKT]VMCLPÊçeOPMWmJG
