§º§¿¶óîóº½¶¾²§º°ó–°»¼¶ óûpf|tró`
Y
U
Vtu
YzúÙ·¶ °¡º£§º¼½óîó’ó¹¼¦¡½¶ªó§»¡¼¦´»ó§º¾¶ó²½·ó £²°¶ýó–°»¼¶ ó¼µó²½°º¶½§ó¿²½· ó±¿¶½·ó¤º§»óµ¦§¦¡º §º°ó¥º º¼½ ÿó°²£§¦¡º½´ó§»¶ó¶  ¶½°¶ó¼µó§»¶ó£² §ó²½·óµ¦§¦¡¶óº½ó²ó ¼¦½· °²£¶ó¼µó¥º±¡²½§ó¶½¶¡´ªýÙ£¡¼¾£§óîó–½¶¡´¶§º°ó¾º··¿¶þ¶² §¶¡½ó±¶²§ÿó§¡²·º§º¼½²¿ó£¶¡°¦  º¼½ó±¿¶½·¶·ó¤º§»ó¾¼·¶¡½ó¶¿¶°§¡¼½º°ó¶¿¶¾¶½§ ÿó¥º±¡²½§ó¼¦·ó¾¶¿¼·º¶ ÿóº½§¶½ ¶ó¡»ª§»¾ó »ºµ§ ÿó·ª½²¾º°ó ¼¦½· °²£¶ÿó±¼§»ó¾²¿¶ó²½·óµ¶¾²¿¶ó¥¼°²¿ ÿó£¿²ªµ¦¿ó²½·ó´¡º§§ªÙ°¼¥¶¡’¡§ƒ¡¼¾£§óîó•¦§¦¡º §º°ó·¶ ¶¡§ó¿²½· °²£¶ó²§ó§¤º¿º´»§ÿó ¿¶¶¸ó·¡¼½¶ ó»¼¥¶¡º½´ó²±¼¥¶ó²½°º¶½§ó¡¦º½ ÿó¥º±¡²½§ó²½·ó¿¦¾º½¼¦ ó°¼¿¼¡ ÿó±¿¶½·º½´ó§¡²·º§º¼½²¿ó²½·ó °ºþµºó²¶ §»¶§º° ÿó°²£§º¥²§º½´ó²½·ó¾ª §¶¡º¼¦ ó²§¾¼ £»¶¡¶Ù µ«óîó·¶ ¶¡§ó¤º½·ó¤»º £¶¡ ÿó¡»ª§»¾º°ó°¿²££º½´ÿó¼¦·ó §¡¦¾¾º½´ÿó¶¿¶°§¡¼½º°ó£¦¿ ¶ ÿó¶°»¼º½´ó°»²½§ Ù¥¼°²¿ óîó¾²¿¶ó²½·óµ¶¾²¿¶ó¥¼°²¿ ÿó§¡²·º§º¼½²¿ó¾º··¿¶þ¶² §¶¡½ó §ª¿¶ÿó¿²ª¶¡¶·ó»²¡¾¼½º¶ ÿó¡»ª§»¾º°ó£»¡² º½´Ù¥¼°²¿ €§¡¦°§¦¡¶·óîó¶½¶¡´¶§º°ó¾º··¿¶þ¶² §¶¡½ó§¡²°¸ÿó¶½´²´º½´óº½§¡¼ó²½·ó£¼¤¶¡µ¦¿ó¼¦§¡¼ó¤º§»ó·ª½²¾º°ó¡»ª§»¾ ÿóµ¶²§¦¡º½´ó»²¡¾¼½º°ó¾²¿¶ó²½·óµ¶¾²¿¶ó¥¼°²¿ Ù¸¶ª¤¼¡· óîó¤¼¡¿·±¶²§ó¾º··¿¶¶² §¶¡½ó¶¿¶°§¡¼½º°óµ¦ º¼½ó°º½¶¾²§º°ó¥º±¡²½§ó§¡²·º§º¼½²¿óµ¦§¦¡º §º°ó ¼¦½·§¡²°¸ó·ª½²¾º°ó¼¦·ó¶°»¼¶ ó¡»ª§»¾º°ó¾¼¼·¥º±¶ Ù°¼·¶²¾¶óîó²§°»¶¡óº½ó§»¶óª¶Ù±£¾óîóâàãÙ´¶½¡¶š½£¦§óîóÙ£¡¼¾£§š½£¦§óîó‡¡²°¸óº½ £º¡¶·ó±ªót
W
Vf
[bó
Yj
Q
[{ót
W{fb
Yóþób|~ót
T
[ta
Yóáãááót
Wj{ót{
[ót
W~btb
Týó† ¶ó º¾º¿²¡ó¾¦ º°²¿ó¥º±¶ÿó¾¼¼·ÿó §ª¿¶ÿó´¶½¡¶ÿóº½ §¡¦¾¶½§ ýÙ¿¶§§¶¡óîóÙº½°¿¦·¶…¼°²¿óîó•²¿ ¶Ù²££…¶¡ º¼½óîó¥áãáæãëâêÙ·¦¡²§º¼½óîóáãêêæáÙÙ¿ª¡º° óîóˆº½§¡¼óþó·¶ ¶¡§ó¤»º £¶¡ ŽÙÙˆ¥¶¡ ¶óâóþó’½°º¶½§ó–°»¼¶ ŽÙpf|tróyj{bót
Wa
V
UÙ
R
Yó
Q
W{ót
Wf~btr_óy
U{eót
W~
YtzÙp
W
[t
Uót
W
Vte
Yóy
Wy
Q
Yó{t
W
V`y
Q{
WÙt
Tya_ót
Tya_ó
Vjót
Wv
Y
QtjÙÙˆƒ¡¶þ»¼¡¦ óþó»ª§»¾º°óƒ¦¿ ¶ŽÙv
Y
Qtjtyót
W
Q
W{_óy|
R
Qót
W|
VÙpf
[tyót
Wb
Yt~_óy
T
V`ó{t
Wp`btbÙÙˆ»¼¡¦ óþó›²¡¾¼½º°ó•¦ º¼½ŽÙ
YtttttttÙ
Tt
Tt
TtttttÙÙˆ‘¡º·´¶óþó‡º¾¶¿¶  ó™¼¦¡½¶ªŽÙb~
Wzó{
Wtó~|
[|Ùp~
Wt
Vóy
U`ó
R
Yót
Wp
R
QÙp
[
[
Tóp
[
[
Tóp
[
[
[
[
[ÙÙˆ¼¦§¡¼óþó–°»¼º½´ó€º¿¶½°¶ŽÙÙ¡¶²§¶·ó±ªó’‡óƒ¿²ª¶¡Ù»§§£ éüü¤¤¤ý²§£¿²ª¶¡ý°¼¾ÙÙ¼£ª¡º´»§ózóáãáæó’¸§º óš½°ý