PMPHAaGHMTWA@aGLKAWaGKWaGHMTWE@KW.@AWGVMTPMKJmJEGMP]KBWLE@KSWSLAVAAGLKAW@EJGAPLVKQCLJAKJ	HMPWPVAAPWPLAVL]PLIKBHMBATQHWAWSMPLRMFVEJPAJAVC]
mJWTMVA@F]PLAWP]HAKBgEVHvAJ@EV
.TVKITPaJAVCAPMG@EJGAPVEGOMJBAGPMKQWVL]PLIRMFVEJPW]JPLWTQHWEPMJCFEWW@VMRMJCFAEPQTHMBPMJCIAHK@]BAIEHARKGEHAJAVCAPMGEJ@HMRAH].GKRAVeVPtVKITPbQPQVMWPMGGMP]WGETAMHHQIMJEPA@F]JAKJHMCLPWWLMIIAVMJCVABHAGPMKJWKJVEMJ	WKEOA@WPVAAPWIK@AVJEJ@RMFVEJPSMPLEPKQGLKBI]WPAV].WB\GMP]EIFMEJGAWQFPHAAGLKAWVL]PLIMGBKKPWPATW@MWPEJPGMP]WKQJ@W.RKGEHWBAIEHARKGEHAJAVCAPMG@AHMRAV]HMRAH]EJ@WTMVMPA@.RKGEHWwPVQGPQVA@TKTWPATPVEGOSMPLCKK@MJPVKEJ@JMGAKQPVKMJGHQ@MJCWKIA@VKTWSMPLIAHK@MGBAIEHARKGEH.OA]SKV@W@EJGAAHAGPVKJMGW]JPLSERATKTRETKVSERAJAKJRMFAWGMP]WGETABQPQVMWPMGgEVHvAJ@EV.GK@AjEIA~KVVK.FTI.CAJVAmJTQP.TVKITPmJTQPpVEGOMJWTMVA@F]gEVHvAJ@EV	aVMOE
qWAWMIMHEVIQWMGEHRMFAIKK@WP]HACAJVAMJWPVQIAJPW
.HAPPAV~.MJGHQ@ArKGEHbEHWA.ETTrAVWMKJR.@QVEPMKJ..H]VMGW..gVAEPA@F]eptHE]AV.LPPTWSSS
EPTHE]AV
GKI..gKT]VMCLPÊçeOPMWmJG
