PMPHAnE@AaIFAVWaIFVEGA.@AWGVMTPMKJeNKQVJA]PLVKQCLIKKVHEJ@WEJ@MJJAVVAEHIWEFAEGKJKBPVQPLMJPLAWLE@KSW
mJWTMVA@F]nEJAa]VAWUQMAPWPVAJCPLEJ@PLARMFVEJPLAEVPBAHPWPKV]PAHHMJCWP]HAKBiEJKVEIEwKJCW
.TVKITPiAHK@MGmJ@MEJBMHIWGKVAFHAJ@KBPVE@MPMKJEHoAVEHEBKHOVL]PLIWEJ@GKJPAITKVEV]KVGLAWPVEHEVVEJCAIAJPWWKQHBQHWPVMJCWVAWKJEJPPEFHEEJ@IVM@EJCEIARKGEPMRABHQPAIAHK@MAWHQWLW]JPLTE@WCAJPHATAVGQWWMKJFQMH@	QTPKEWSAATMJCGLKVQWSMPLIAHK@MGA\TVAWWMRAIEHAEJ@BAIEHARKGEHWVKIEJPMGEJ@WHMCLPH]IAHEJGLKHMG
.GKRAVeVPtVKITPbQPQVMWPMGGMP]WGETAEP@QWOCHKSMJCSMPLJAKJHMCLPWMJAIAVEH@EJ@NE@ALQAWELKHKCVETLMGTVKNAGPMKJKBMJPAVPSMJA@BHKVEHTEPPAVJWHMOANEWIMJAKVHKPQWWLMIIAVMJCEFKRAWKBP@MCMPEHVEMJWPVAEOWGKJPAITKVEV]EJ@WHAAO@AWMCJWGM	BMVKIEJPMGMWILMCL	PAGLCHKSWLEVTBKGQWKJMJPVMGEPA@APEMHWGMJAIEPMGHMCLPMJCQHPVE	IK@AVJEAWPLAPMG
.WB\wKBPPEFHEPETW@MWPEJPBHQPAPVMHHWCAJPHAWPVMJCWSAHHWW]JPLTE@LQIWQFPHA@MCMPEHFAHHGLMIAWEIFMAJPGVKS@IQVIQVWHMOAEBMHIWAPSMJ@GLMIAW
.RKGEHWiAHK@MGIEHAEJ@BAIEHARKGEHWA\TVAWWMRAEJ@AIKPMKJEH@AHMRAV]
.RKGEHWwPVQGPQVA@mJ@MEJBMHI	WP]HAFEHHE@SMPLEWKQHBQHMJPVKFQMH@MJCRAVWAWEWKEVMJCAIKPMKJEHGLKVQWMJWPVQIAJPEHFVM@CABAEPQVMJCBHQPAEJ@WPVMJCWEJ@ECAJPHABE@MJCKQPVKSMPLIAHK@MGIEHAEJ@BAIEHARKGEHW
.OA]SKV@WmJ@MEJbMHItKTiEHE]EHEIbMHIiQWMGfKHH]SKK@tKTsKVH@bQWMKJbMHIwGKVAvKIEJPMGaIKPMKJEHiAHK@MGgMJAIEPMGwKQJ@PVEGOqTHMBPMJCgQHPQVEHfHAJ@lAEVPBAHPinE]EGLEJ@VEJ.GK@AjEIAnEJAa]VA.FTI.CAJVAmJTQP.TVKITPmJTQPpVEGOMJWTMVA@F]iEJKVEIEwKJCW	oMJCMJMOEPPQXiEHHQwMJCLXqJJMiQOQJ@EJXoQJGLEGOKfKFEJXinE]EGLEJ@VEJXfMNQiAJKJ
qWAWMIMHEVIQWMGEHRMFAIKK@WP]HACAJVAMJWPVQIAJPW
.HAPPAVn.MJGHQ@ArKGEHbEHWA.ETTrAVWMKJR.@QVEPMKJ..H]VMGW..gVAEPA@F]eptHE]AV.LPPTWSSS
EPTHE]AV
GKI..gKT]VMCLPÊçeOPMWmJG
