PMPHAqVFEJtQHWA.@AWGVMTPMKJ`EJGAPLVKQCLPLAGMP]WPVAAPWSLAVAVL]PLIIAAPWHMCLP
mJWTMVA@F]PLARMFVEJPFAEPWKBpwAVMAWPLMWPVEGOGETPQVAWPLAWTMVMPKBIKRAIAJPEJ@GAHAFVEPMKJ
.TVKITPaJAVCAPMG@EJGAPVEGORMFVEJPmJ@MEJMJBHQAJGAW@VMRMJCTAVGQWWMKJ@]JEIMGVL]PLIHMRAH]PEFHEFAEPWAHAGPVMB]MJCW]JPLWIEHAEJ@BAIEHARKGEHWWTMVMPA@EJ@BAWPMRAIKK@.GKRAVeVPtVKITPeBQPQVMWPMGGMP]WGETAFEPLA@MJJAKJHMCLPWFQWPHMJCWPVAAPWSMPLLKHKCVETLMG@MWTHE]WRMFVEJPGKHKVWEJ@EHMRAH]AJAVCAPMGEPIKWTLAVA
pLAWGAJAMWBMHHA@SMPLIKRAIAJPEJ@VL]PLIGETPQVMJCPLAAWWAJGAKBEIK@AVJ@EJGABAWPMREH
.WB\GMP]EIFMEJGAVL]PLIMGGHETWPEFHEAGLKAWW]JPLAPMGWSKKWLAWGVKS@GLAAVWEIM@WPIQWMG.RKGEHWIEHAEJ@BAIEHARKGEHWHMRAH]@QAP@]JEIMGEJ@VL]PLIMGSMPLTHE]BQHMJPAVEGPMKJW.RKGEHWwPVQGPQVA@@EJGAPVEGOSMPLEJAJCECMJCMJPVKEJ@RMFVEJPKQPVKBAEPQVMJCWAEIHAWW@VKTWSMPLHMRAH]IEHAEJ@BAIEHARKGEHW.OA]SKV@W@EJGAFKHH]SKK@AHAGPVKJMGMJ@MEJBQWMKJBAWPMRAFAEPWSKVH@IQWMGQVFEJRMFAWJAKJHMCLPWGAHAFVEPMKJ@EJGAIQWMGpwi.GK@AjEIAqH]WWAW.FTI.CAJVAmJTQP.TVKITPmJTQPpVEGOMJWTMVA@F]pwAVMAW	bQHHwKJCiQUEFHEXwPVAAP`EJGAV`XevvELIEJtVEFLQ@ARErEVQJ`wLVE@@LEopEJMWLOf
qWAWMIMHEVIQWMGEHRMFAIKK@WP]HACAJVAMJWPVQIAJPW
.HAPPAVq.MJGHQ@ArKGEHbEHWA.ETTrAVWMKJR.@QVEPMKJ..H]VMGWMJPVKFAEPy..RAVWA∆§∑gMP]eSEOAJWy.vL]PLIWAGLKPLVKQCLGVKS@A@HEJAW.gKHKVW@EJGAMJRMFVEJPVEMJW.pLATQHWAKBPLAGMP]JARAVWHAATW.mJARAV]GKVJAVHMBAHAETW
..GLKVQW∆§∑qVFEJgAHAFVEPMKJy.EEEEELLLLL.KKKKK.`EJGASMPLPLAHMCLPWQJ@AVPLAWO].bAAHPLAFAEPHAPWTMVMPWBH]
..RAVWA∆§∑wPVAAPw]ITLKJ]y.mJPLALAEVPKBPLAQVFEJIE^A.iAHK@MAWSAERAMJE@E^^HMJCLE^A.rKMGAWFHAJ@MJENK]KQWWKQJ@.mJPLMWVL]PLIBVAA@KIMWBKQJ@
..FVM@CA∆§∑jAKJ`VAEIWy.MMMMMMMMMMMMMM.KKKKKK.jAKJ@VAEIWAHAGPVMGJMCLP.mJPLMWGMP]SAMCJMPA
..KQPVK∆§∑bAWPMRAaGLKy.AGLKMJCFAEPW.KKKKKKK.pLA@EJGAKBHMBAMJRMFVEJPWPVAAPW
..gVAEPA@F]eptHE]AV.LPPTWSSS
EPTHE]AV
GKI..gKT]VMCLPÊçeOPMWmJG
